# Generated by Django 5.1.2 on 2024-10-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
